/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_tasks_stack(void);
void enable_processor_faults(void);
__attribute__((naked)) void switch_sp_to_psp(void);
uint32_t get_psp_value(void);
void update_next_task(void);
void save_psp_value(uint32_t current_psp_value);
void task_delay(uint32_t tick_count);

/* some stack memory calculation*/
#define SIZE_TASK_STACK  1024U  //U代表無符號
#define SIZE_SCHED_STACK 1024U

#define SRAM_START 0x20000000U
#define SIZE_SRAM  ((128)*(1024))
#define SRAM_END ((SRAM_START)+(SIZE_SRAM))

#define T1_STACK_START SRAM_END
#define T2_STACK_START ((SRAM_END)-(SIZE_TASK_STACK))
#define T3_STACK_START ((SRAM_END)-(2*SIZE_TASK_STACK))
#define T4_STACK_START ((SRAM_END)-(3*SIZE_TASK_STACK))
#define IDLE_STACK_START ((SRAM_END)-(4*SIZE_TASK_STACK))
#define SCHED_STACK_START ((SRAM_END)-(5*SIZE_TASK_STACK))

#define TICK_HZ 1000
#define SYSTICK_TIM_CLK 16000000U

#define MAX_TASKS 5
#define DUMMY_XPSR 0x01000000U

#define TASK_READY_STATE 0x00
#define TASK_BLOCKED_STATE 0xFF

uint32_t task_handlers[MAX_TASKS];
uint8_t current_task =1; // mean task1 is running


typedef struct{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void(*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{

	enable_processor_faults();//啟用錯誤偵測

	init_scheduler_stack(SCHED_STACK_START);//MSP

	init_tasks_stack();// 初始化 以儲存虛擬幀

	init_systick_timer(TICK_HZ);//生成systick計時器異常

	switch_sp_to_psp();//在這行上面是使用MSP

	task1_handler();

	for(;;);
}

void idle_task(void){
	while(1);
}

void task1_handler(void){
	while(1){
		printf("THIS IS TASK1\n ");
		task_delay(1000);
	}
}
void task2_handler(void){
	while(1){
		printf("THIS IS TASK2\n ");
		task_delay(500);
	}
}
void task3_handler(void){
	while(1){
		printf("THIS IS TASK3\n ");
		task_delay(250);
	}
}
void task4_handler(void){
	while(1){
		printf("THIS IS TASK4\n ");
		task_delay(125);
	}
}
// 系統計數器
void init_systick_timer(uint32_t tick_hz){
	uint32_t* pSRVR = (uint32_t*)0xE000E014;//SRVR地址
	uint32_t* pSCSR = (uint32_t*)0xE000E010;//CSR地址
	uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz)-1;//Reload value= N-1;
	// Clear the value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);
	// load the value in to SVR
	*pSRVR |= count_value;
	// change CSR
	*pSCSR |=(1<<1);//Enables SysTick exception request:
	*pSCSR |=(1<<2);//Indicates the clock source:
	*pSCSR |=(1<<0);//Enables the counter:
}









__attribute__((naked)) void switch_sp_to_psp(void){
	//利用控制寄存器
	//1.initialize the PSP with TASK1 stack start adderss
	//get the value of psp of current task
	__asm volatile ("PUSH {LR}"); //preserve LR which connects back to main()
	__asm volatile ("BL get_psp_value");//跑到上面的函式 值會存到 R0
	__asm volatile ("MSR PSP,R0"); // initialize psp
	__asm volatile ("POP {LR}"); // pops back LR value
	//2.change SP to PSP using CONTROL register
	__asm volatile ("MOV R0,#0X02");
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");// return from function call
}

//MSP 初始化
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack){
	__asm volatile("MSR MSP,%0"::"r"(sched_top_of_stack):);
	__asm volatile("BX LR");
}




//PSP初始化
void init_tasks_stack(void){

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;


	uint32_t* pPSP;
	for(int i=0 ; i<MAX_TASKS;i++){
		pPSP=(uint32_t*) user_tasks[i].psp_value;
		pPSP--;
		*pPSP=DUMMY_XPSR; // 0x01000000
		pPSP--;//pc
		*pPSP=(uint32_t)user_tasks[i].task_handler;
		pPSP--;//LR
		*pPSP=0xFFFFFFFD; // ret
		for(int j =0;j<13;j++){ //R0~R12
			pPSP--;
			*pPSP=0;
		}
		user_tasks[i].psp_value=(uint32_t)pPSP;
	}
}

void save_psp_value(uint32_t current_psp_value){
	user_tasks[current_task].psp_value=current_psp_value;
}

void update_next_task(void){
	int state = TASK_BLOCKED_STATE;

	for (int i = 0;i<(MAX_TASKS);i++){
		current_task++;
		current_task = current_task% MAX_TASKS;//(1->2->3->0)
		state = user_tasks[current_task].current_state;
		if((state == TASK_READY_STATE)&&(current_task !=0)){
			break;
		}
	}
	if (state != TASK_READY_STATE){
		current_task=0;
	}


}

uint32_t get_psp_value(void){
	return user_tasks[current_task].psp_value;
}

uint32_t g_tick_count= 0;

void schedule(void){
	uint32_t *pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= (1<<28);
}


void task_delay(uint32_t tick_count){
	if(current_task == 0){
		user_tasks[current_task].block_count = g_tick_count+tick_count;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}
}

__attribute__((naked)) void PendSV_Handler(void){
	/*Save the context of current task*/
		//1.Get current running task PSP value
	__asm volatile("MRS R0,PSP");
		//2.Using the PSP value store SF2(R4 to R11)
	__asm volatile("STMDB R0!,{R4-R11}");//Store Multiple registers, decrement before //R0 stored address
	__asm volatile("PUSH {LR}");
		//驚嘆號是每個值都能得到更新
		//3.Save the current value of PSP
	__asm volatile("BL save_psp_value");


		/*Retrieve the context of next task*/
		//1. Decide next task ro run
	__asm volatile("BL update_next_task");
		//2. get its past PSP value
	__asm volatile("BL get_psp_value");
		//3. Using that PSP value retrieve SF2(R4 to R11)
	__asm volatile("LDMIA R0!,{R4-R11}");//多個輸入
		//4. update PSP and exit
	__asm volatile("MSR PSP,R0");//psp現在指向下一個更新任務
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");
}


void updated_global_tick_count(void){
	g_tick_count++;
}

void unblock_task(void){
	for(int i =1 ; i<MAX_TASKS;i++){
		if(user_tasks[i].current_state !=TASK_READY_STATE){
			if(user_tasks[i].block_count == g_tick_count){
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}
}

void SysTick_Handler(void){
	uint32_t *pICSR = (uint32_t*)0xE000ED04; // ICSR

	updated_global_tick_count();
	unblock_task();
	*pICSR |= (1<<28); // 啟用PendSV

}




// 錯誤檢測
void enable_processor_faults(void){
	uint32_t *pSHCSR = (uint32_t*) 0xE000ED24;
	*pSHCSR|= (1<<16);//mem manage
	*pSHCSR|= (1<<17);//bus fault
	*pSHCSR|= (1<<18);//usage fault
}

void HardFault_Handler(void)
{
	printf("Exception :Hardfault\n");
	while(1);
}
void MemMangae_Handler(void)
{
	printf("Exception :MemMangefault\n");
	while(1);
}
void BusFault_Handler(void)
{
	printf("Exception :Busfault\n");
	while(1);
}
